format='\[ $directory\]$character '
right_format='\[ $all\]'
add_newline = false
scan_timeout = 50
command_timeout = 500

[line_break]
disabled = true

[character]
format = '[](green bold)'

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 2

[golang]
symbol = "ﳑ "

[python]
symbol = " "

[gcloud]
format = '[$symbol($project)]($style) '
