#!/usr/bin/env zsh

if [[ ! -v INSIDE_GENIE ]]; then
    echo "Starting genie..."
    exec /usr/bin/genie -s
    clear
fi

# autostart zsh agent
if [ $(ps aux | grep ssh-agent | wc -l) -eq 1 ]; then
  eval "$(ssh-agent -s)"
fi
