if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then
    export PATH="$HOME/.local/bin:$PATH"
    exec startx
fi

# wsl spesific
if [[ ! -v INSIDE_GENIE ]]; then
    echo "Starting genie..."
    exec /usr/bin/genie -s
fi
