# cordless:
  # This is a GO program that generates a cordless colorscheme.
  # The color values have been turned into pywal variables.
  # This program is run, and the produced
  # theme.json is put into $HOME/.config/cordless/
  # path: /home/gideon/.cache/wal/cordless.go

# oomoxicons:
  # # This changes depending on your iconset
  # command: "oomox-archdroid-icons-cli"
  # # Path to the desired theme you want to apply
  # themepath: "/home/cocatrip/.oomox/scripted_colors/xresources/xresources-reverse"

oomoxgtk:
  # Path to the desired theme you want to apply
  themepath: "/usr/share/oomox/scripted_colors/xresources/xresources-reverse"

# oomoxspotify:
  # spotifypath: "/usr/libexec/spotify/Apps"
  # enabled: "True"

# slickpywal:
  # path:

# pywalneopixels:
  # path:

# waldiscord:
  # path:
 
# razer-cli:
  # path: 

telegrampalletegen:
  path: "/home/cocatrip/.telegram-palette-gen/"

spicetify:
  path: "/home/cocatrip/.spicetify-cli/"

pywalfox:
  path: "/home/cocatrip/.local/bin/"  

# xmenu:
  # path: "/home/gideon/Programs/xmenu"

# starttree:
  # path: "/home/Projects/StartTree/"

# Custom commands to be run when chameleon is run.
# Use at your own risk
# hooks:
  # echosuccess: "echo 'success, theme applied'"
  # startTree:
    # command: "docker-compose -f docker-compose.yaml restart StartTree"
    # directory: "/home/gideon/Projects/StartTree/docker/"
