k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: false
  logoless: true
  crumbsless: true
  readOnly: false
  noExitOnCtrlC: false
  noIcons: true
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 1000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: true
  currentContext: bpr-dev
  currentCluster: bpr-dev
  clusters:
    bpr-dev:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - tekton-pipelines
        - administrasi
        - default
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    bpr-uat:
      namespace:
        active: jenkins
        lockFavorites: false
        favorites:
        - jenkins
        - administrasi
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    bpr-uat-mvp1:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - jenkins-uat
        - default
      view:
        active: service
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-cocatrip
